version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - three_tier_todo_network
    volumes:
      - mongodb_volume:/data/db

  backend:
    image: rasyar/todo-backend:${IMAGE_TAG}
    container_name: todo-backend
    ports:
      - "3100:3100"
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/todo?authSource=admin
      - PORT=3100
    networks:
      - three_tier_todo_network
    depends_on:
      - mongodb
    restart: on-failure

  frontend:
    image: rasyar/todo-frontend:${IMAGE_TAG}
    container_name: todo-frontend
    ports:
      # 3000 on browser -> 80 nginx
      - "3000:80"
    networks:
      - three_tier_todo_network
    depends_on:
      - backend
    restart: on-failure
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - three_tier_todo_network
    depends_on:
      - mongodb
    restart: on-failure

networks:
  three_tier_todo_network:
    driver: bridge

volumes:
  mongodb_volume:
