---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    MONGO_ROOT_PASSWORD: AgBf7e3mbrEckgyngGkil9RlA/vDIDGVGwRIHYGIbaypovCK1RWTfneU/Rob96CVssmmMR503cZrX3hstGJsuhGnDlSKSC7YeS62lGAS8VeGV1NN5KS3qDjhqu9z5XiLlAhoz8x+1Qq8+IwE/msGiQt2lE+zAotCrgn6uiKCQoHKpjxPbW7SUAeKO1VfYHJiVnnht15T/s1rTlCXZjXfJZFjId/Us3gGrW/ph6rClNqh5lfl2pLbO2t6rxZMESaQ1MH8HspDddPyPNSAEkzedHIREfN6sNQpj1fiE6lzYK9rPO/n5YBfaOJqjQc9b+Qn7GGnyvbclVgGXzvA9Vh4QbcsPyDJNr7mHydKfGbQeYDcxuDSqBikWqocmOCNVhY5dtzeK+6CY6Fva3NNN/7lVrpnWFPHCHhB/hPJQG/oi2u/pBM+p1C1GlWsSsscA02lwoY8QaembgqGG2gL+MiNoRMBy4hIK4OxCekj4p48fivNwS9/bjzdwSs61q7c6knDKm2DIqWwxBnSoXSELeLqNjBfxDDAWgah9KGpmdAfeCN5niltCk8m8KTXsC76qKDxhsE0hO6RLsO0qwmy/glYScVy4nkj4DjQCEbCRlNfDz6Cv0sJd/1NHLBHTAApOvvWDrVo56UKj7dWsOmAnWsNuJYBxsI0cZGZNSSnH+ciH45Ddth1rhUwyfmgkUx+VPzAdHCnJvfWVBZbZA==
    MONGO_ROOT_USERNAME: AgBvriyo0quCEAlVCb4kYREq1HUN1ATNvdeMG+UBTiJ+ZuCY8Toe/06nOKLo2pUWw+iDD2wEthyb9ewEcuHsk1UGwFFtRcPbZggLVsda2YTKuutsf3g5x8IDUn50pqmDNGW5UQeT3VrR4u7XNFNgw3x4byeg9cp0kSN0GvVKEGiRCduIixppJzxp8OAFIgFv8KwwjJ6rcpeYDhXWBuHlmk5aw2UrJrWvobmCvjukPYtbsS3Qxo/ZGsMBDO5+5fgmfd1HNosDBZCiXtWlnmtivoudXbaY9Ln5j/Dacj4uWlyd+zmQpUrEzYW4YihqLX/3FIcMPpwRxhLxCqyh773D+0W3q6iohezCWJa/1uxXJkEMGK45n8YRENTyAiMjHK/kZAnKkbLM9doenDxrtwOkg94jC6HAIi2uYf/ZYsSDNjGzS8xyZOkHY+1Z/cy1hgbLi6ZvUPMFTZ7IlN5s0TrwE+AxKo1+alaF7whvI/ivnchAh+tgKT7Q+AB2UCWD8gCrqixDeJARVRmtRMbChkm5Jo1XBKuUaHw2cIjdk15GEiBMoW0Q2hZgmPpIV/UI4SYxdBUfej6ki/LTTLw6Bt0zyGZGe/nmqZFkeLBLMeJrB2lPV65HmXxcGrBK1TcfkomOJQ8Yfffpz6umtSYT4GoQ/6RsDIJMHCYdcxVx/CqrVsQsdQwQgHcCO+Aq4C/ZKqLUUNvwJCEI
  template:
    metadata:
      name: mongodb-secret
      namespace: default
    type: Opaque
